//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarpetCleaningEntities : DbContext
    {
        public CarpetCleaningEntities()
            : base("name=CarpetCleaningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCarpetPrice> tblCarpetPrices { get; set; }
        public virtual DbSet<tblCarpet> tblCarpets { get; set; }
        public virtual DbSet<tblDocument> tblDocuments { get; set; }
        public virtual DbSet<tblLog> tblLogs { get; set; }
        public virtual DbSet<tblLogType> tblLogTypes { get; set; }
        public virtual DbSet<tblNote> tblNotes { get; set; }
        public virtual DbSet<tblPersonnelFunction> tblPersonnelFunctions { get; set; }
        public virtual DbSet<tblPersonnel> tblPersonnels { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblCheck> tblChecks { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblFactor> tblFactors { get; set; }
        public virtual DbSet<tblCustomerBuy> tblCustomerBuys { get; set; }
        public virtual DbSet<tblFactorsList> tblFactorsLists { get; set; }
        public virtual DbSet<tblCustomerBuyList> tblCustomerBuyLists { get; set; }
    }
}
