//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblBakhsh> tblBakhshes { get; set; }
        public virtual DbSet<tblOtagh> tblOtaghs { get; set; }
        public virtual DbSet<tblPaziresh> tblPazireshes { get; set; }
        public virtual DbSet<tblPezeshk> tblPezeshks { get; set; }
        public virtual DbSet<tblTasviyeHeasb> tblTasviyeHeasbs { get; set; }
    }
}
