//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarpetPrice
    {
        public int CarpetPriceID { get; set; }
        public int Year { get; set; }
        public decimal Shur { get; set; }
        public decimal Darkesh { get; set; }
        public decimal Gayegh { get; set; }
        public decimal Shiraze { get; set; }
        public decimal Charm { get; set; }
        public decimal Hasiri { get; set; }
        public decimal Geytani { get; set; }
        public decimal Pardakht { get; set; }
        public string Description { get; set; }
        public string RegisterDate { get; set; }
    }
}
