//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCheck
    {
        public decimal CheckID { get; set; }
        public short CheckTypeID { get; set; }
        public string CheckSerial { get; set; }
        public string CheckDate { get; set; }
        public string CheckDueDate { get; set; }
        public int CustomerID { get; set; }
        public decimal Price { get; set; }
        public string BankName { get; set; }
        public bool Reminder { get; set; }
        public int ReminderDay { get; set; }
        public string ReminderDate { get; set; }
        public string Description { get; set; }
        public string RegisterDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
