//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarpet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCarpet()
        {
            this.tblPersonnelFunctions = new HashSet<tblPersonnelFunction>();
            this.tblFactorsLists = new HashSet<tblFactorsList>();
        }
    
        public int CarpetID { get; set; }
        public string Title { get; set; }
        public double Width { get; set; }
        public double Hight { get; set; }
        public double Area { get; set; }
        public double Shur { get; set; }
        public double Darkesh { get; set; }
        public double Gayegh { get; set; }
        public double Shiraze { get; set; }
        public double Charm { get; set; }
        public double Hasiri { get; set; }
        public double Geytani { get; set; }
        public double Pardakht { get; set; }
        public string Description { get; set; }
        public string RegisterDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonnelFunction> tblPersonnelFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFactorsList> tblFactorsLists { get; set; }
    }
}
