//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocument
    {
        public decimal DocumentID { get; set; }
        public short DocumetnTypeID { get; set; }
        public string DocumentDate { get; set; }
        public string Title { get; set; }
        public short PriceTypeID { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public decimal CheckID { get; set; }
        public int CustomerID { get; set; }
        public string Description { get; set; }
        public string RegisterDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
