//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public decimal LogID { get; set; }
        public int LogTypeID { get; set; }
        public int UserID { get; set; }
        public string LogContent { get; set; }
        public string TableName { get; set; }
        public decimal TableKeyID { get; set; }
        public string LogDate { get; set; }
        public string LogTime { get; set; }
    
        public virtual tblLogType tblLogType { get; set; }
    }
}
