//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOtagh
    {
        public int OtaghID { get; set; }
        public string CodeOtagh { get; set; }
        public int BakshID { get; set; }
    
        public virtual tblBakhsh tblBakhsh { get; set; }
    }
}
