//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaziresh
    {
        public int PazireshID { get; set; }
        public string TarikhPaziresh { get; set; }
        public int BimarID { get; set; }
        public int DoctorID { get; set; }
    
        public virtual tblBimar tblBimar { get; set; }
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblTasviyeHeasb tblTasviyeHeasb { get; set; }
    }
}
