//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPersonnel()
        {
            this.tblPersonnelFunctions = new HashSet<tblPersonnelFunction>();
        }
    
        public int PersonnelID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Image { get; set; }
        public string NationCode { get; set; }
        public string Id { get; set; }
        public bool SexType { get; set; }
        public short MaritalStatus { get; set; }
        public string FatherName { get; set; }
        public string BithayDay { get; set; }
        public string CityOfBirth { get; set; }
        public string CityOfLife { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Description { get; set; }
        public short Active { get; set; }
        public string RegisterDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonnelFunction> tblPersonnelFunctions { get; set; }
    }
}
