//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaziresh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPaziresh()
        {
            this.tblTasviyeHeasbs = new HashSet<tblTasviyeHeasb>();
        }
    
        public int PazireshID { get; set; }
        public string TarikhPaziresh { get; set; }
        public int PezeshkID { get; set; }
        public int OtaghID { get; set; }
        public string NameBimar { get; set; }
        public string LastNameBimar { get; set; }
        public string CodeMelliBimar { get; set; }
        public string CodeBimeBimar { get; set; }
    
        public virtual tblOtagh tblOtagh { get; set; }
        public virtual tblPezeshk tblPezeshk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTasviyeHeasb> tblTasviyeHeasbs { get; set; }
    }
}
