//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTasviyeHeasb
    {
        public int TasviyeHeasbID { get; set; }
        public int PazireshID { get; set; }
        public long Mablagh { get; set; }
        public string TarikhTasviyeHeasb { get; set; }
    
        public virtual tblPaziresh tblPaziresh { get; set; }
    }
}
