//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Image { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Mobile { get; set; }
        public string BackGroundImage { get; set; }
        public string Description { get; set; }
        public short Active { get; set; }
        public string RegisterDate { get; set; }
    }
}
